nelmio_api_doc:
    documentation:
        info:
            title: Traiteur API
            description: Documentation de l'API Traiteur Vite & Gourmand.
            version: 1.0.0
        components:
            securitySchemes:
                ApiToken:
                    type: apiKey
                    in: header
                    name: X-AUTH-TOKEN
        security:
            - ApiToken: []

    areas:
        path_patterns:
            - ^/api(?!/doc$)